Repository LexiconGr7-1/gladiator-management-simulator, pull requests merged in 2022-04, with the labels that each got.

#47 #43 create custom fetch hook
  Gladiator.Presentation.Ui/src/hooks/useFetch.js
  Gladiator.Presentation.Ui/src/pages/GladiatorEditPage.js
  Gladiator.Presentation.Ui/src/pages/GladiatorEditPage.test.js
  Gladiator.Presentation.Ui/src/routes/Views.js
  gladiator.presentation.ui/Gladiator.Presentation.Ui.esproj
  gladiator.presentation.ui/public/index.html
  gladiator.presentation.ui/src/pages/GladiatorDetailsPage.js
  gladiator.presentation.ui/src/pages/GladiatorDetailsPage.test.js
  gladiator.presentation.ui/src/pages/GladiatorListPage.js
Labels: feature, frontend

#48 #44 Add player controller
  Gladiator.Presentation.Api/Controllers/ArenaController.cs
  Gladiator.Presentation.Api/Controllers/PlayerController.cs
Labels: backend

#52 #45 Create arena controller
  Gladiator.Presentation.Api/Controllers/ArenaController.cs
  Gladiator.Presentation.Api/Controllers/PlayerController.cs
  Gladiator.Presentation.Api/Gladiator.Presentation.Api.csproj
  Gladiator.Presentation.Api/Models/Arena.cs
  Gladiator.Presentation.Api/Models/GladiatorSchool.cs
  Gladiator.Presentation.Api/Models/Player.cs
Labels: feature, backend

#53 #50 Create player pages
  Gladiator.Presentation.Ui/src/pages/GladiatorCreatePage.js
  Gladiator.Presentation.Ui/src/pages/GladiatorCreatePage.test.js
  Gladiator.Presentation.Ui/src/pages/GladiatorEditPage.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerCreatePage.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerCreatePage.test.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerDetailsPage.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerDetailsPage.test.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerEditPage.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerEditPage.test.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerListPage.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerListPage.test.js
  Gladiator.Presentation.Ui/src/routes/Views.js
  gladiator.presentation.ui/src/pages/GladiatorListPage.test.js
Labels: feature, frontend, ux/ui

#40 #34 create layout
  Gladiator.Presentation.Ui/src/Components/Layout/Footer.js
  Gladiator.Presentation.Ui/src/Components/Layout/Header.js
  Gladiator.Presentation.Ui/src/Components/Layout/Layout.js
  Gladiator.Presentation.Ui/src/Components/Layout/TopNavBar.js
  Gladiator.Presentation.Ui/src/index.js
  Gladiator.Presentation.Ui/src/pages/GladiatorCreatePage.js
  gladiator.presentation.ui/src/App.js
  gladiator.presentation.ui/src/index.js
Labels: frontend, ux/ui

#55 #46 create gladiator school pages
  Gladiator.Presentation.Ui/src/pages/school/SchoolCreatePage.js
  Gladiator.Presentation.Ui/src/pages/school/SchoolCreatePage.test.js
  Gladiator.Presentation.Ui/src/pages/school/SchoolDetailsPage.js
  Gladiator.Presentation.Ui/src/pages/school/SchoolDetailsPage.test.js
  Gladiator.Presentation.Ui/src/pages/school/SchoolEditPage.js
  Gladiator.Presentation.Ui/src/pages/school/SchoolEditPage.test.js
  Gladiator.Presentation.Ui/src/pages/school/SchoolListPage.js
  Gladiator.Presentation.Ui/src/pages/school/SchoolListPage.test.js
  Gladiator.Presentation.Ui/src/routes/Views.js
Labels: feature, frontend, ux/ui

#75 #73 Generate gladiator
  Gladiator.Presentation.Api/Controllers/GladiatorController.cs
Labels: feature, backend

#77 #76 Create CRUD for player pages
  Gladiator.Presentation.Api/Controllers/PlayerController.cs
  Gladiator.Presentation.Ui/src/pages/GladiatorCreatePage.js
  Gladiator.Presentation.Ui/src/pages/GladiatorCreatePage.test.js
  Gladiator.Presentation.Ui/src/pages/GladiatorEditPage.test.js
  Gladiator.Presentation.Ui/src/pages/LandingPage.js
  Gladiator.Presentation.Ui/src/pages/LandingPage.test.js
  Gladiator.Presentation.Ui/src/pages/NotFound.js
  Gladiator.Presentation.Ui/src/pages/NotFound.test.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerCreatePage.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerCreatePage.test.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerDetailsPage.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerDetailsPage.test.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerEditPage.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerEditPage.test.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerListPage.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerListPage.test.js
  gladiator.presentation.ui/src/App.test.js
  gladiator.presentation.ui/src/pages/GladiatorDetailsPage.js
Labels: enhancement, fix, feature, backend, frontend

#83 #81 Create CRUD for arena pages
  Gladiator.Presentation.Api/Controllers/ArenaController.cs
  Gladiator.Presentation.Api/Controllers/PlayerController.cs
  Gladiator.Presentation.Api/Models/Arena.cs
  Gladiator.Presentation.Ui/src/Components/Checkbox.js
  Gladiator.Presentation.Ui/src/Components/Layout/Footer.js
  Gladiator.Presentation.Ui/src/Components/Layout/Layout.js
  Gladiator.Presentation.Ui/src/Components/arena/edit/AvailableSchools.js
  Gladiator.Presentation.Ui/src/Components/arena/edit/SchoolsInArena.js
  gladiator.presentation.ui/src/pages/arena/ArenaCreatePage.js
  gladiator.presentation.ui/src/pages/arena/ArenaDetailsPage.js
  gladiator.presentation.ui/src/pages/arena/ArenaEditPage.js
  gladiator.presentation.ui/src/pages/arena/ArenaListPage.js
Labels: enhancement, fix, feature, backend, frontend

#85 #84 Create CRUD for school pages
  Gladiator.Presentation.Api/Controllers/GladiatorSchoolController.cs
  Gladiator.Presentation.Ui/src/pages/school/SchoolCreatePage.js
  Gladiator.Presentation.Ui/src/pages/school/SchoolDetailsPage.js
  Gladiator.Presentation.Ui/src/pages/school/SchoolEditPage.js
  Gladiator.Presentation.Ui/src/pages/school/SchoolListPage.js
Labels: enhancement, feature, frontend

#89 #87 Pages into subdirectories
  Gladiator.Presentation.Ui/src/pages/gladiator/GladiatorCreatePage.js
  Gladiator.Presentation.Ui/src/pages/gladiator/GladiatorCreatePage.test.js
  Gladiator.Presentation.Ui/src/pages/gladiator/GladiatorDetailsPage.js
  Gladiator.Presentation.Ui/src/pages/gladiator/GladiatorDetailsPage.test.js
  Gladiator.Presentation.Ui/src/pages/gladiator/GladiatorEditPage.js
  Gladiator.Presentation.Ui/src/pages/gladiator/GladiatorEditPage.test.js
  Gladiator.Presentation.Ui/src/pages/gladiator/GladiatorListPage.js
  Gladiator.Presentation.Ui/src/pages/gladiator/GladiatorListPage.test.js
  Gladiator.Presentation.Ui/src/pages/player/PlayerCreatePage.test.js
  Gladiator.Presentation.Ui/src/pages/school/SchoolCreatePage.test.js
  Gladiator.Presentation.Ui/src/routes/Views.js
  gladiator.presentation.ui/src/pages/arena/ArenaDetailsPage.test.js
  gladiator.presentation.ui/src/pages/arena/ArenaEditPage.test.js
  gladiator.presentation.ui/src/pages/arena/ArenaListPage.test.js
Labels: enhancement, fix, frontend
